//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Data.Reports {
    
    public partial class OfferLetter_OF_PB : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "WebApp.Data.Reports.OfferLetter_OF_PB.repx");

            // Controls
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.xrRichText32 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText32");
            this.xrPageInfo1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("xrPageInfo1");
            this.xrRichText31 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText31");
            this.xrRichText28 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText28");
            this.xrRichText27 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText27");
            this.xrRichText26 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText26");
            this.xrRichText25 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText25");
            this.xrRichText24 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText24");
            this.xrRichText21 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText21");
            this.xrRichText20 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText20");
            this.xrRichText19 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText19");
            this.xrRichText18 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText18");
            this.xrRichText17 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText17");
            this.xrRichText16 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText16");
            this.xrRichText15 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText15");
            this.xrRichText14 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText14");
            this.xrRichText13 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText13");
            this.xrRichText5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText5");
            this.xrRichText12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText12");
            this.xrRichText11 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText11");
            this.xrRichText10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText10");
            this.xrRichText9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText9");
            this.xrRichText8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText8");
            this.xrRichText7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText7");
            this.xrRichText4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText4");
            this.xrRichText2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText2");
            this.xrRichText1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText1");
            this.xrPictureBox1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPictureBox>("xrPictureBox1");
            this.xrRichText3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText3");
            this.xrRichText6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText6");
            this.xrRichText22 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText22");
            this.xrRichText23 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText23");
            this.xrRichText29 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText29");

            // Parameters
            this.fullName = reportInitializer.GetParameter("fullName");
            this.PositionNameVie = reportInitializer.GetParameter("PositionNameVie");
            this.PositionNameEng = reportInitializer.GetParameter("PositionNameEng");
            this.WorkingPlace = reportInitializer.GetParameter("WorkingPlace");
            this.BasicSalary = reportInitializer.GetParameter("BasicSalary");
            this.Benefit8 = reportInitializer.GetParameter("Benefit8");
            this.PercentSal = reportInitializer.GetParameter("PercentSal");
            this.numMonthPB = reportInitializer.GetParameter("numMonthPB");
            this.jobStartDate = reportInitializer.GetParameter("jobStartDate");
            this.sumSal = reportInitializer.GetParameter("sumSal");

            // Calculated Fields
            this.sumSalary = reportInitializer.GetCalculatedField("sumSalary");
        }
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.XRRichText xrRichText32;
        private DevExpress.XtraReports.UI.XRPageInfo xrPageInfo1;
        private DevExpress.XtraReports.UI.XRRichText xrRichText31;
        private DevExpress.XtraReports.UI.XRRichText xrRichText28;
        private DevExpress.XtraReports.UI.XRRichText xrRichText27;
        private DevExpress.XtraReports.UI.XRRichText xrRichText26;
        private DevExpress.XtraReports.UI.XRRichText xrRichText25;
        private DevExpress.XtraReports.UI.XRRichText xrRichText24;
        private DevExpress.XtraReports.UI.XRRichText xrRichText21;
        private DevExpress.XtraReports.UI.XRRichText xrRichText20;
        private DevExpress.XtraReports.UI.XRRichText xrRichText19;
        private DevExpress.XtraReports.UI.XRRichText xrRichText18;
        private DevExpress.XtraReports.UI.XRRichText xrRichText17;
        private DevExpress.XtraReports.UI.XRRichText xrRichText16;
        private DevExpress.XtraReports.UI.XRRichText xrRichText15;
        private DevExpress.XtraReports.UI.XRRichText xrRichText14;
        private DevExpress.XtraReports.UI.XRRichText xrRichText13;
        private DevExpress.XtraReports.UI.XRRichText xrRichText5;
        private DevExpress.XtraReports.UI.XRRichText xrRichText12;
        private DevExpress.XtraReports.UI.XRRichText xrRichText11;
        private DevExpress.XtraReports.UI.XRRichText xrRichText10;
        private DevExpress.XtraReports.UI.XRRichText xrRichText9;
        private DevExpress.XtraReports.UI.XRRichText xrRichText8;
        private DevExpress.XtraReports.UI.XRRichText xrRichText7;
        private DevExpress.XtraReports.UI.XRRichText xrRichText4;
        private DevExpress.XtraReports.UI.XRRichText xrRichText2;
        private DevExpress.XtraReports.UI.XRRichText xrRichText1;
        private DevExpress.XtraReports.UI.XRPictureBox xrPictureBox1;
        private DevExpress.XtraReports.UI.XRRichText xrRichText3;
        private DevExpress.XtraReports.UI.XRRichText xrRichText6;
        private DevExpress.XtraReports.UI.XRRichText xrRichText22;
        private DevExpress.XtraReports.UI.XRRichText xrRichText23;
        private DevExpress.XtraReports.UI.XRRichText xrRichText29;
        private DevExpress.XtraReports.UI.CalculatedField sumSalary;
        private DevExpress.XtraReports.Parameters.Parameter fullName;
        private DevExpress.XtraReports.Parameters.Parameter PositionNameVie;
        private DevExpress.XtraReports.Parameters.Parameter PositionNameEng;
        private DevExpress.XtraReports.Parameters.Parameter WorkingPlace;
        private DevExpress.XtraReports.Parameters.Parameter BasicSalary;
        private DevExpress.XtraReports.Parameters.Parameter Benefit8;
        private DevExpress.XtraReports.Parameters.Parameter PercentSal;
        private DevExpress.XtraReports.Parameters.Parameter numMonthPB;
        private DevExpress.XtraReports.Parameters.Parameter jobStartDate;
        private DevExpress.XtraReports.Parameters.Parameter sumSal;
    }
}
