//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Data.Reports {
    
    public partial class PrintDecisionPB : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "WebApp.DataProtection.Reports.PrintDecisionPB.repx");

            // Controls
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.reportHeaderBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("reportHeaderBand1");
            this.PageFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageFooterBand>("PageFooter");
            this.label1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label1");
            this.table2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table2");
            this.table1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table1");
            this.xrLabel2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel2");
            this.xrLabel8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel8");
            this.xrLabel20 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel20");
            this.xrLabel3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel3");
            this.xrRichText31 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText31");
            this.xrRichText5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText5");
            this.xrRichText4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText4");
            this.xrRichText32 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText32");
            this.xrRichText24 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText24");
            this.xrRichText23 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText23");
            this.xrRichText25 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText25");
            this.xrRichText26 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText26");
            this.xrRichText33 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText33");
            this.xrRichText34 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText34");
            this.xrRichText35 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText35");
            this.xrLabel15 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel15");
            this.xrRichText36 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText36");
            this.xrRichText38 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText38");
            this.xrLabel17 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel17");
            this.xrRichText39 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText39");
            this.xrLabel18 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel18");
            this.xrRichText40 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText40");
            this.xrLabel19 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel19");
            this.xrRichText27 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText27");
            this.xrRichText28 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText28");
            this.xrLabel16 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel16");
            this.xrRichText30 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText30");
            this.xrRichText3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText3");
            this.xrRichText6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText6");
            this.xrLabel5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel5");
            this.xrRichText7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText7");
            this.xrRichText8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText8");
            this.xrLabel7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel7");
            this.xrRichText9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText9");
            this.xrLabel10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel10");
            this.xrLabel12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel12");
            this.xrRichText12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText12");
            this.xrRichText11 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText11");
            this.xrLabel11 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel11");
            this.xrRichText10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText10");
            this.xrRichText16 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText16");
            this.xrLabel13 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel13");
            this.xrRichText15 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText15");
            this.xrLabel14 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel14");
            this.xrRichText18 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText18");
            this.xrRichText17 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText17");
            this.xrRichText19 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText19");
            this.xrRichText21 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText21");
            this.xrRichText20 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText20");
            this.xrRichText22 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText22");
            this.xrRichText41 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText41");
            this.xrRichText44 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText44");
            this.xrRichText14 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText14");
            this.xrRichText13 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText13");
            this.xrLabel4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel4");
            this.xrLabel6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel6");
            this.xrLabel9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel9");
            this.xrRichText29 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText29");
            this.xrRichText1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText1");
            this.xrRichText2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText2");
            this.tableRow2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow2");
            this.tableCell2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell2");
            this.tableRow1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow1");
            this.tableCell1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell1");

            // Data Sources
            this.sqlDataSource1 = reportInitializer.GetDataSource<DevExpress.DataAccess.Sql.SqlDataSource>("sqlDataSource1");

            // Styles
            this.Title = reportInitializer.GetStyle("Title");
            this.DetailCaption3 = reportInitializer.GetStyle("DetailCaption3");
            this.DetailData3 = reportInitializer.GetStyle("DetailData3");
            this.DetailData3_Odd = reportInitializer.GetStyle("DetailData3_Odd");
            this.DetailCaptionBackground3 = reportInitializer.GetStyle("DetailCaptionBackground3");
            this.PageInfo = reportInitializer.GetStyle("PageInfo");
        }
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.ReportHeaderBand reportHeaderBand1;
        private DevExpress.XtraReports.UI.PageFooterBand PageFooter;
        private DevExpress.XtraReports.UI.XRLabel label1;
        private DevExpress.XtraReports.UI.XRTable table2;
        private DevExpress.XtraReports.UI.XRTable table1;
        private DevExpress.XtraReports.UI.XRLabel xrLabel2;
        private DevExpress.XtraReports.UI.XRLabel xrLabel8;
        private DevExpress.XtraReports.UI.XRLabel xrLabel20;
        private DevExpress.XtraReports.UI.XRLabel xrLabel3;
        private DevExpress.XtraReports.UI.XRRichText xrRichText31;
        private DevExpress.XtraReports.UI.XRRichText xrRichText5;
        private DevExpress.XtraReports.UI.XRRichText xrRichText4;
        private DevExpress.XtraReports.UI.XRRichText xrRichText32;
        private DevExpress.XtraReports.UI.XRRichText xrRichText24;
        private DevExpress.XtraReports.UI.XRRichText xrRichText23;
        private DevExpress.XtraReports.UI.XRRichText xrRichText25;
        private DevExpress.XtraReports.UI.XRRichText xrRichText26;
        private DevExpress.XtraReports.UI.XRRichText xrRichText33;
        private DevExpress.XtraReports.UI.XRRichText xrRichText34;
        private DevExpress.XtraReports.UI.XRRichText xrRichText35;
        private DevExpress.XtraReports.UI.XRLabel xrLabel15;
        private DevExpress.XtraReports.UI.XRRichText xrRichText36;
        private DevExpress.XtraReports.UI.XRRichText xrRichText38;
        private DevExpress.XtraReports.UI.XRLabel xrLabel17;
        private DevExpress.XtraReports.UI.XRRichText xrRichText39;
        private DevExpress.XtraReports.UI.XRLabel xrLabel18;
        private DevExpress.XtraReports.UI.XRRichText xrRichText40;
        private DevExpress.XtraReports.UI.XRLabel xrLabel19;
        private DevExpress.XtraReports.UI.XRRichText xrRichText27;
        private DevExpress.XtraReports.UI.XRRichText xrRichText28;
        private DevExpress.XtraReports.UI.XRLabel xrLabel16;
        private DevExpress.XtraReports.UI.XRRichText xrRichText30;
        private DevExpress.XtraReports.UI.XRRichText xrRichText3;
        private DevExpress.XtraReports.UI.XRRichText xrRichText6;
        private DevExpress.XtraReports.UI.XRLabel xrLabel5;
        private DevExpress.XtraReports.UI.XRRichText xrRichText7;
        private DevExpress.XtraReports.UI.XRRichText xrRichText8;
        private DevExpress.XtraReports.UI.XRLabel xrLabel7;
        private DevExpress.XtraReports.UI.XRRichText xrRichText9;
        private DevExpress.XtraReports.UI.XRLabel xrLabel10;
        private DevExpress.XtraReports.UI.XRLabel xrLabel12;
        private DevExpress.XtraReports.UI.XRRichText xrRichText12;
        private DevExpress.XtraReports.UI.XRRichText xrRichText11;
        private DevExpress.XtraReports.UI.XRLabel xrLabel11;
        private DevExpress.XtraReports.UI.XRRichText xrRichText10;
        private DevExpress.XtraReports.UI.XRRichText xrRichText16;
        private DevExpress.XtraReports.UI.XRLabel xrLabel13;
        private DevExpress.XtraReports.UI.XRRichText xrRichText15;
        private DevExpress.XtraReports.UI.XRLabel xrLabel14;
        private DevExpress.XtraReports.UI.XRRichText xrRichText18;
        private DevExpress.XtraReports.UI.XRRichText xrRichText17;
        private DevExpress.XtraReports.UI.XRRichText xrRichText19;
        private DevExpress.XtraReports.UI.XRRichText xrRichText21;
        private DevExpress.XtraReports.UI.XRRichText xrRichText20;
        private DevExpress.XtraReports.UI.XRRichText xrRichText22;
        private DevExpress.XtraReports.UI.XRRichText xrRichText41;
        private DevExpress.XtraReports.UI.XRRichText xrRichText44;
        private DevExpress.XtraReports.UI.XRRichText xrRichText14;
        private DevExpress.XtraReports.UI.XRRichText xrRichText13;
        private DevExpress.XtraReports.UI.XRLabel xrLabel4;
        private DevExpress.XtraReports.UI.XRLabel xrLabel6;
        private DevExpress.XtraReports.UI.XRLabel xrLabel9;
        private DevExpress.XtraReports.UI.XRRichText xrRichText29;
        private DevExpress.XtraReports.UI.XRRichText xrRichText1;
        private DevExpress.XtraReports.UI.XRRichText xrRichText2;
        private DevExpress.XtraReports.UI.XRTableRow tableRow2;
        private DevExpress.XtraReports.UI.XRTableCell tableCell2;
        private DevExpress.XtraReports.UI.XRTableRow tableRow1;
        private DevExpress.XtraReports.UI.XRTableCell tableCell1;
        private DevExpress.DataAccess.Sql.SqlDataSource sqlDataSource1;
        private DevExpress.XtraReports.UI.XRControlStyle Title;
        private DevExpress.XtraReports.UI.XRControlStyle DetailCaption3;
        private DevExpress.XtraReports.UI.XRControlStyle DetailData3;
        private DevExpress.XtraReports.UI.XRControlStyle DetailData3_Odd;
        private DevExpress.XtraReports.UI.XRControlStyle DetailCaptionBackground3;
        private DevExpress.XtraReports.UI.XRControlStyle PageInfo;
    }
}
